import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Diff, GitCompareArrows, PencilLine, PlusCircle } from "lucide-react";
import { useStudio } from "../state/store";
import { api } from "../utils/api";
import { compareTables, type TableComparison } from "../utils/tableCompare";
import { tokenize } from "../utils/sql";
import { Btn, Badge, Spinner } from "./ui";

const CLS: Record<string, string> = {
  kw: "text-[var(--syn-kw)] font-semibold", fn: "text-[var(--syn-fn)]", str: "text-[var(--syn-str)]",
  num: "text-[var(--syn-num)]", cmt: "text-[var(--syn-cmt)] italic", op: "text-[var(--syn-op)]", ident: "", ws: "",
};

/** How many source tables we compare before stopping (each costs two metadata fetches). */
const MAX_TABLES = 250;
/** Metadata fetches to run at once — matches the server's poolMax of 4 per connection,
 *  so this never queues more requests than the pool can serve at once. */
const CONCURRENCY = 4;

type TableStatus = "new" | "changed" | "same";
interface TableResult {
  name: string;
  status: TableStatus;
  cmp: TableComparison;
}
interface CompareOutcome {
  results: TableResult[];
  targetOnly: string[];
  truncated: boolean;
}

/** Run `fn` over `items` with bounded concurrency, preserving order. */
async function mapLimit<T, R>(items: T[], limit: number, fn: (t: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  const worker = async () => {
    while (next < items.length) {
      const i = next++;
      out[i] = await fn(items[i]);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return out;
}

export default function MigrationAssistant() {
  const s = useStudio();
  const oracleConns = useMemo(() => s.connections.filter((c) => c.engine === "oracle"), [s.connections]);

  const [sourceId, setSourceId] = useState(() => oracleConns[0]?.id ?? "");
  const [targetId, setTargetId] = useState(() => oracleConns[1]?.id ?? oracleConns[0]?.id ?? "");
  const [phase, setPhase] = useState<"setup" | "comparing" | "results">("setup");
  const [outcome, setOutcome] = useState<CompareOutcome | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [applying, setApplying] = useState(false);

  const sourceName = oracleConns.find((c) => c.id === sourceId)?.name ?? "—";
  const targetName = oracleConns.find((c) => c.id === targetId)?.name ?? "—";

  const actionable = outcome?.results.filter((r) => r.status !== "same") ?? [];
  const inSync = outcome?.results.filter((r) => r.status === "same").length ?? 0;

  const script = useMemo(() => {
    if (!outcome) return "";
    const picked = actionable.filter((r) => selected.has(r.name));
    if (!picked.length) return "";
    const header = `-- Migration: ${sourceName} -> ${targetName}\n-- Generated by Oracle DataForge on ${new Date().toISOString().slice(0, 10)}\n-- ${picked.length} of ${actionable.length} object(s) selected\n`;
    const body = picked
      .map((r) => `-- Table: ${r.name} (${r.status === "new" ? "create in target" : "structural drift"})\n${r.cmp.sync.join("\n")}`)
      .join("\n\n");
    return `${header}\n${body}`;
  }, [outcome, actionable, selected, sourceName, targetName]);

  const runCompare = async () => {
    setError(null);
    setPhase("comparing");
    setOutcome(null);
    try {
      const [srcSchema, tgtSchema] = await Promise.all([api.schema(sourceId), api.schema(targetId)]);
      const targetTables = new Set(tgtSchema.tables.map((t) => t.name.toUpperCase()));
      const allSource = srcSchema.tables.map((t) => t.name);
      const truncated = allSource.length > MAX_TABLES;
      const sourceTables = allSource.slice(0, MAX_TABLES);

      const results = await mapLimit(sourceTables, CONCURRENCY, async (name): Promise<TableResult> => {
        const [srcMeta, tgtMeta] = await Promise.all([api.tableMeta(sourceId, name), api.tableMeta(targetId, name)]);
        const cmp = compareTables(srcMeta, tgtMeta);
        const status: TableStatus = !tgtMeta.exists ? "new" : cmp.identical ? "same" : "changed";
        return { name, status, cmp };
      });

      const sourceSet = new Set(sourceTables.map((t) => t.toUpperCase()));
      const targetOnly = tgtSchema.tables.map((t) => t.name).filter((n) => !sourceSet.has(n.toUpperCase()));

      setOutcome({ results, targetOnly, truncated });
      setSelected(new Set(results.filter((r) => r.status !== "same").map((r) => r.name)));
      setPhase("results");
    } catch (e) {
      setError((e as Error).message);
      setPhase("setup");
    }
  };

  const toggle = (name: string) =>
    setSelected((sel) => {
      const n = new Set(sel);
      if (n.has(name)) n.delete(name);
      else n.add(name);
      return n;
    });

  const pickedStatements = () =>
    actionable.filter((r) => selected.has(r.name)).flatMap((r) => r.cmp.sync);

  const apply = () => {
    const statements = pickedStatements();
    const creates = actionable.filter((r) => selected.has(r.name) && r.status === "new").length;
    const drops = actionable.filter((r) => selected.has(r.name)).reduce((n, r) => n + r.cmp.sync.filter((x) => /\bDROP\b/i.test(x)).length, 0);
    s.askConfirm({
      title: `Apply migration to ${targetName}?`,
      body:
        `${statements.length} statement(s) across ${selected.size} table(s) will run against ${targetName}.` +
        (creates ? ` ${creates} new table(s) will be created.` : "") +
        (drops ? ` ⚠ Includes ${drops} column/index DROP(s) that permanently remove data or objects.` : " No destructive statements selected."),
      confirmLabel: "Apply migration",
      danger: drops > 0,
      onConfirm: async () => {
        setApplying(true);
        try {
          const res = await api.applyTableDdl(targetId, statements, true);
          if (res.failed) {
            const firstErr = res.results.find((r) => !r.ok);
            s.toast("error", `Migration stopped after ${res.applied}/${statements.length}: ${firstErr?.error ?? "error"}`);
          } else {
            s.toast("success", `Migration applied to ${targetName} — ${res.applied} statement(s)`);
            // structure changed on the target — refetch if it's the active connection
            if (targetId === s.activeConnId) s.bumpSchema();
            await runCompare();
          }
        } catch (e) {
          s.toast("error", `Apply failed: ${(e as Error).message}`);
        } finally {
          setApplying(false);
        }
      },
    });
  };

  if (oracleConns.length === 0) {
    return (
      <div className="h-full flex items-center justify-center p-8 text-center text-mute text-[12.5px]">
        Schema comparison needs a live Oracle connection. Create one in the sidebar first.
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto p-4 df-fade">
      <div className="flex items-center gap-2 mb-1">
        <GitCompareArrows size={16} className="text-accent" />
        <h2 className="text-[14px] font-semibold">Schema compare &amp; migration</h2>
      </div>
      <p className="text-[11.5px] text-mute mb-4">
        Compares every table in the source schema against the target and builds an ordered script that brings the target in line — Oracle connections, tables only (columns, indexes, constraints, comments).
      </p>

      {/* source/target picker */}
      <div className="flex items-end gap-3 flex-wrap mb-4">
        <label className="block">
          <div className="text-[11px] font-semibold text-soft mb-1 uppercase tracking-wider">Source (reference)</div>
          <select value={sourceId} onChange={(e) => setSourceId(e.target.value)} aria-label="Source connection" className="h-8 px-2 rounded-md bg-panel2 border border-bdr text-[12.5px] focus:border-accent focus:outline-none min-w-56">
            {oracleConns.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
        </label>
        <ArrowRight size={16} className="text-mute mb-2" />
        <label className="block">
          <div className="text-[11px] font-semibold text-soft mb-1 uppercase tracking-wider">Target (to be updated)</div>
          <select value={targetId} onChange={(e) => setTargetId(e.target.value)} aria-label="Target connection" className="h-8 px-2 rounded-md bg-panel2 border border-bdr text-[12.5px] focus:border-accent focus:outline-none min-w-56">
            {oracleConns.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
        </label>
        <Btn variant="primary" onClick={runCompare} className="mb-0.5" disabled={phase === "comparing" || sourceId === targetId} title={sourceId === targetId ? "Pick two different connections" : "Compare schemas"}>
          <Diff size={13} /> Compare schemas
        </Btn>
      </div>

      {error && (
        <div className="border border-err/40 bg-err/8 rounded-lg p-3 text-[12.5px] text-ink mb-4">
          <span className="text-err font-semibold">Compare failed:</span> {error}
        </div>
      )}

      {phase === "comparing" && (
        <div className="py-16 flex justify-center">
          <Spinner label={`Comparing tables in ${sourceName} against ${targetName}…`} />
        </div>
      )}

      {phase === "results" && outcome && (
        <div className="df-fade">
          {actionable.length === 0 ? (
            <div className="border border-ok/40 bg-ok/8 rounded-lg p-4 flex items-start gap-2.5">
              <CheckCircle2 size={16} className="text-ok shrink-0 mt-0.5" />
              <div className="text-[12.5px]">
                <div className="font-semibold text-ink">Schemas are structurally in sync.</div>
                <div className="text-mute mt-0.5">{inSync} table(s) compared, no differences found.{outcome.targetOnly.length ? ` ${outcome.targetOnly.length} table(s) exist only in the target (left untouched).` : ""}</div>
              </div>
            </div>
          ) : (
            <div className="grid xl:grid-cols-2 gap-4">
              {/* differences */}
              <section>
                <h3 className="text-[11px] font-bold uppercase tracking-wider text-mute mb-2">
                  {actionable.length} table(s) differ — select which to migrate{inSync ? ` · ${inSync} in sync` : ""}
                </h3>
                <div className="space-y-2">
                  {actionable.map((r) => (
                    <label key={r.name} className={`flex items-start gap-2.5 border rounded-lg p-3 cursor-pointer transition-colors ${selected.has(r.name) ? "border-accent/60 bg-accentdim" : "border-bdr hover:border-accent/40"}`}>
                      <input
                        type="checkbox"
                        checked={selected.has(r.name)}
                        onChange={() => toggle(r.name)}
                        className="mt-0.5 accent-[var(--accent)]"
                        aria-label={`Include ${r.name} in migration`}
                      />
                      {r.status === "new" ? <PlusCircle size={14} className="text-ok shrink-0 mt-0.5" /> : <PencilLine size={14} className="text-warn shrink-0 mt-0.5" />}
                      <div className="min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-mono text-[12.5px] font-semibold">{r.name}</span>
                          <Badge tone={r.status === "new" ? "ok" : "warn"}>{r.status === "new" ? "Missing in target" : "Definition drift"}</Badge>
                          <span className="text-[11px] text-mute">{r.cmp.sync.length} statement(s)</span>
                        </div>
                        <div className="text-[11.5px] text-mute mt-0.5">
                          {r.status === "new"
                            ? `Create ${r.name} in the target (${r.cmp.columns.length} columns).`
                            : diffSummary(r.cmp)}
                        </div>
                      </div>
                    </label>
                  ))}
                </div>
                {outcome.truncated && (
                  <p className="text-[11px] text-warn mt-2">Only the first {MAX_TABLES} source tables were compared.</p>
                )}
                {outcome.targetOnly.length > 0 && (
                  <p className="text-[11px] text-mute mt-2">
                    {outcome.targetOnly.length} table(s) exist only in the target and are left untouched (drop them from the worksheet if intended): <span className="font-mono">{outcome.targetOnly.slice(0, 8).join(", ")}{outcome.targetOnly.length > 8 ? "…" : ""}</span>
                  </p>
                )}
              </section>

              {/* generated script */}
              <section className="min-w-0">
                <h3 className="text-[11px] font-bold uppercase tracking-wider text-mute mb-2">Generated migration script</h3>
                <pre className="font-mono text-[11.5px] leading-5 whitespace-pre overflow-auto p-3 bg-panel2 border border-bdr rounded-lg max-h-[420px]">
                  {script
                    ? tokenize(script).map((t, i) => <span key={i} className={CLS[t.cls]}>{t.text}</span>)
                    : <span className="text-mute italic">Select one or more tables to build the script.</span>}
                </pre>
                <div className="mt-3 flex gap-2 flex-wrap">
                  <Btn variant="primary" onClick={apply} disabled={selected.size === 0 || applying}>
                    {applying ? "Applying…" : "Apply to target"}
                  </Btn>
                  <Btn
                    variant="outline"
                    onClick={() => { s.setSql(script); s.openTab("worksheet", "Worksheet 1"); s.toast("info", "Migration script loaded in worksheet"); }}
                    disabled={!script}
                  >
                    Open in worksheet
                  </Btn>
                </div>
              </section>
            </div>
          )}
        </div>
      )}

      {phase === "setup" && !error && (
        <div className="border border-dashed border-bdr rounded-xl p-10 text-center text-mute text-[12.5px]">
          Pick a source and target Oracle connection, then run <b className="text-soft">Compare schemas</b> to see structural differences and generate an ordered migration script.
        </div>
      )}
    </div>
  );
}

/** Short human summary of a changed table's diffs. */
function diffSummary(cmp: TableComparison): string {
  const parts: string[] = [];
  const colAdd = cmp.columns.filter((c) => c.status === "sourceOnly").length;
  const colDrop = cmp.columns.filter((c) => c.status === "targetOnly").length;
  const colMod = cmp.columns.filter((c) => c.status === "changed").length;
  if (colAdd) parts.push(`+${colAdd} col`);
  if (colDrop) parts.push(`-${colDrop} col`);
  if (colMod) parts.push(`~${colMod} col`);
  const ixAdd = cmp.indexes.filter((i) => i.status === "sourceOnly").length;
  const ixDrop = cmp.indexes.filter((i) => i.status === "targetOnly").length;
  if (ixAdd || ixDrop) parts.push(`${ixAdd + ixDrop} index`);
  const conAdd = cmp.constraints.filter((c) => c.status === "sourceOnly").length;
  const conDrop = cmp.constraints.filter((c) => c.status === "targetOnly").length;
  if (conAdd || conDrop) parts.push(`${conAdd + conDrop} constraint`);
  if (cmp.tableCommentDiff) parts.push("comment");
  return parts.length ? parts.join(", ") : "structural drift";
}
